# Generated by Django 4.2 on 2023-04-12 18:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elevator", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elevator",
            name="request",
        ),
    ]
