# Generated by Django 4.2 on 2023-04-12 20:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("elevator", "0002_remove_elevator_request"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="request",
            name="floor_no",
        ),
        migrations.AddField(
            model_name="request",
            name="elevator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="elevator.elevator",
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="floor",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="request",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
